version: "3.9"

services:
  santa:
    container_name: dpbhai/mysecretsanta:01
    build:
      context: .
    ports:
      - 8081:8080
    volumes:
      - ./target:/usr/src/app/target
    restart: always
